# Common
mod_version=9.0.0-beta.1
mod_id=simplycaterpillar
mod_name=Simply Caterpillar
mod_authors=Daniel-Mendes
mod_description=Adds a caterpillar drill to Minecraft.
mod_credits=Anyone who has contributed to the project and special thanks to Blockbench for the amazing tool.
mod_licence=LGPL-3.0-or-later

# Minecraft
minecraft_version=1.21.5
minecraft_version_range=[1.21.5, 1.22)

# Fabric
fabric_loader_version=0.16.14
fabric_api_version=0.126.0+1.21.5

# NeoForge
neoforge_version=21.5.75

# Architectury
architectury_api_version=16.1.4

# Parchment
parchment_minecraft=1.21.5
parchment_version=2025.06.01

# Project
maven_group=dev.the_fireplace.caterpillar
java_version=21
archives_name=simplycaterpillar
enabled_platforms=fabric,neoforge

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true