modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/The-Fireplace/Simply-Caterpillar/issues"

[[mods]] #mandatory
modId="simplycaterpillar"
version="1.19-1-0"
displayName="Simply Caterpillar"
#updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-caterpillar"
logoFile="simplycaterpillar.png"
credits="Daniel Appleby for the original Caterpillar mod"
authors="The_Fireplace, Daniel-Mendes"
description="Adds a caterpillar drill to Minecraft."

[[dependencies.simplycaterpillar]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplycaterpillar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
