modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/The-Fireplace/Simply-Caterpillar/issues"

[[mods]] #mandatory
modId="${modId}"
version="${modVersion}"
displayName="Simply Caterpillar"
#updateJSONURL=""
displayURL="https://github.com/The-Fireplace/Simply-Caterpillar/"
logoFile="simplycaterpillar.png"
credits="Daniel Appleby for the original Caterpillar mod"
authors="The_Fireplace, Daniel-Mendes"
description="${modDescription}"

[[dependencies.simplycaterpillar]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplycaterpillar]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"

[modproperties.jei]
    catalogueImageIcon="simplycaterpillar.png"