modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
license = "${modLicense}"
issueTrackerURL = "${modIssueTrackerURL}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modDisplayName}"
updateJSONURL = "${modUpdateJson}"
displayURL = "${modDisplayURL}"
logoFile = "${modLogoFile}"
credits = "Daniel Appleby for the original Caterpillar mod"
authors = "The_Fireplace, Daniel-Mendes"
description = "${modDescription}"

[custom.mc-publish]
modrinth = "${modrinthId}"
curseforge = "${curseForgeId}"

[[dependencies.simplycaterpillar]]
modId = "forge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplycaterpillar]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"