modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "simplycaterpillar"
version = "${version}"
displayName = "Simply Caterpillar"
authors = "Daniel-Mendes"
description = '''
Adds a caterpillar drill to Minecraft.
'''
#logoFile = ""

[[dependencies.simplycaterpillar]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplycaterpillar]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplycaterpillar]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "simplycaterpillar.mixins.json"
