# This workflow will build a Java project with Gradle

name: Java CI with Gradle

on:
  push:
    branches: [ feature/1.19 ]
  pull_request:
    branches: [ feature/1.19 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
    - name: Upload artifact JAR
      uses: actions/upload-artifact@v3
      with:
        name: Simply-Caterpillar_JAR
        path: build/libs/*.jar
